// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsizHn8c3MOoGB3sm1Wb06Sf3xwzEGi4Q',
    appId: '1:232057901176:web:8264798bfcfbe5f02edd8d',
    messagingSenderId: '232057901176',
    projectId: 'real-time-chat-applicati-850bb',
    authDomain: 'real-time-chat-applicati-850bb.firebaseapp.com',
    storageBucket: 'real-time-chat-applicati-850bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBC6Mwvhss9sICnDIFz5lJJbs9LA8PUs',
    appId: '1:232057901176:android:c2cf5e3d0f538bd02edd8d',
    messagingSenderId: '232057901176',
    projectId: 'real-time-chat-applicati-850bb',
    storageBucket: 'real-time-chat-applicati-850bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmXZkxJRO0LbVKy3j-4A3zHniDZgZNObE',
    appId: '1:232057901176:ios:2769f8bd377496ea2edd8d',
    messagingSenderId: '232057901176',
    projectId: 'real-time-chat-applicati-850bb',
    storageBucket: 'real-time-chat-applicati-850bb.appspot.com',
    iosClientId: '232057901176-3ltrkj8t1hkr7kl7ah0fqfrug9ored80.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmXZkxJRO0LbVKy3j-4A3zHniDZgZNObE',
    appId: '1:232057901176:ios:2769f8bd377496ea2edd8d',
    messagingSenderId: '232057901176',
    projectId: 'real-time-chat-applicati-850bb',
    storageBucket: 'real-time-chat-applicati-850bb.appspot.com',
    iosClientId: '232057901176-3ltrkj8t1hkr7kl7ah0fqfrug9ored80.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsizHn8c3MOoGB3sm1Wb06Sf3xwzEGi4Q',
    appId: '1:232057901176:web:679b25ca6387ba2f2edd8d',
    messagingSenderId: '232057901176',
    projectId: 'real-time-chat-applicati-850bb',
    authDomain: 'real-time-chat-applicati-850bb.firebaseapp.com',
    storageBucket: 'real-time-chat-applicati-850bb.appspot.com',
  );
}
